name: train

row_limit: 10
permitted_selfies_length: 175 # CHANGE THIS TO THE ACTUAL PERCENTILE LATER


checkpointing:
  save_dir: ${cwd:}
  resume_from_ckpt: false
  resume_ckpt_path: ${cwd:}/checkpoints/best-v1.ckpt
  fresh_data: true

wandb:
  project: SELFIES-diffusion
  notes: testing a selfies model
  group: null # Groups related runs
  job_type: training # Type of job (e.g., training, evaluation)
  name: reshape # Name of the run
  id: ${.name}_${seed} #Sets unique name and seed
  tags:
    - ${noise.type} # Sets metadata tags for filtering runs
    - ${data.train}
    - ${data.valid}

# This is important when working with multi-GPU training, to ensure that 
# the batch size is divided evenly among all GPUs.
loader:
  global_batch_size: 16
  eval_global_batch_size: ${.global_batch_size}
  # Note: batch_size and eval_batch_size are **per machine**
  batch_size: ${div_up:${.global_batch_size}, ${eval:${mode.trainer.devices} * ${mode.trainer.num_nodes}}}
  eval_batch_size: ${div_up:${.eval_global_batch_size}, ${eval:${mode.trainer.devices} * ${mode.trainer.num_nodes}}}
  num_workers: 4
  pin_memory: True

# This is the config for training the Lightning trainer model
trainer:
  _target_: lightning.Trainer
  accelerator: auto
  strategy: auto # Let lightning choose wtvr
  num_nodes: 1 # Number of machines, which might have multiple GPUs
  devices: ${device_count:}
  accumulate_grad_batches: ${div_up:${mode.loader.global_batch_size}, ${eval:${mode.trainer.devices} * ${mode.loader.batch_size} * ${mode.trainer.num_nodes}}}
  gradient_clip_val: 1.0 # Clip gradients to this value. Prevents exploding gradients
  precision: '32' # BF16 float precision is better. CHANGE FOR LINUX
  num_sanity_val_steps: 1 # Runs 2 validation steps before training
  max_steps: 1_000_000 # Maximum number of training steps
  log_every_n_steps: 10 # log metrics every 10 steps
  limit_train_batches: 1.0   # train on full dataset, can be used to toggle quick run
  limit_val_batches: 1.0     # validate on full dataset, can be used to toggle quick run
  val_check_interval: null # Run validation every epoch (too often right now)
