
# --- Base Paths (Only edit these if your environment changes) ---
base_dir: /scratch/s3905845/thesis_final_coding
data_root: ${paths.base_dir}/data/kraken
outputs_dir: ${paths.base_dir}/outputs/${hydra:job.name}

# --- Data & Preprocessing Paths ---
original_data: ${paths.data_root}/training_data/descriptors_v3.csv
mean_std: ${paths.data_root}/mapping/mean_std.json
bin_edges: ${paths.data_root}/mapping/bin_edges.json
selfies_alphabet: ${paths.data_root}/training_data/selfies_alphabet.txt # Base learned SELFIES tokens (also present in APE)
property_columns: ${paths.data_root}/mapping/property_columns.txt
group_123_properties: ${paths.data_root}/mapping/group_123_properties.txt
rdkit_metrics: ${paths.data_root}/mapping/rdkit_metrics.txt

# --- Dynamically Generated Paths based on experiment config ---
# The tokenizer path changes based on the selected tokenizer config.
tokenizer: ${paths.data_root}/tokenizers/${experiment.name}

# The preprocessed data path can be overridden by the conditioning type (e.g., for prepend).
filtered_original_data: ${paths.data_root}/training_data/filtered_selfies.csv
pre_processed_data: ${paths.data_root}/training_data/preprocessed_data.parquet
train_data_encoding: ${paths.data_root}/training_data/${experiment.name}
selfies_ape_vocab: ${paths.data_root}/tokenizer/ # This is the APE vocabulary for SELFIES, changes for each APE experiment. Should this be hydra dir?
length_histogram: ${paths.data_root}/training_data/length_histogram.json
median_percentile: ${paths.data_root}/training_data/bottom_top_medians.csv

# --- Output Paths For plots and molecules---
metrics_dir: ${paths.data_root}/metric_plots/
temp_path: ${paths.data_root}/sampled_data/temp.tmp
sampled_data: ${paths.data_root}/sampled_data/${experiment.name}/
synthesize_dir: ${paths.data_root}/synthesized_molecules

# Baseline testing paths
tiny_wordlevel: ${paths.data_root}/sampled_data/model_size_tiny/hist_samples_with_properties.json
small_wordlevel: ${paths.data_root}/sampled_data/model_size_small/hist_samples_with_properties.json
ape_70: ${paths.data_root}/sampled_data/ape_70/hist_samples_with_properties.json
ape_80: ${paths.data_root}/sampled_data/ape_80/hist_samples_with_properties.json
ape_110: ${paths.data_root}/sampled_data/ape_110/hist_samples_with_properties.json

# Conditioning paths
baseline_model_path: ${paths.small_wordlevel}
prepend_1: ${paths.data_root}/sampled_data/prepend_1/hist_samples_with_properties.json
prepend_3: ${paths.data_root}/sampled_data/prepend_3/hist_samples_with_properties.json
prepend_8: ${paths.data_root}/sampled_data/prepend_8/hist_samples_with_properties.json
prepend_all: ${paths.data_root}/sampled_data/prepend_all/hist_samples_with_properties.json
embedding_1: ${paths.data_root}/sampled_data/embedding_1/hist_samples_with_properties.json
embedding_3: ${paths.data_root}/sampled_data/embedding_3/hist_samples_with_properties.json
embedding_8: ${paths.data_root}/sampled_data/embedding_8/hist_samples_with_properties.json
embedding_all: ${paths.data_root}/sampled_data/embedding_all/hist_samples_with_properties.json
cfg_03: ${paths.data_root}/sampled_data/0.3_cfg/hist_samples_with_properties.json
cfg_10: ${paths.data_root}/sampled_data/1.0_cfg/hist_samples_with_properties.json
cfg_40: ${paths.data_root}/sampled_data/4.0_cfg/hist_samples_with_properties.json