name: prepend
prepend: True # This turns on the prepending of the conditioning properties e.g., '[vbur_vbur_bin_3|3][F][C][Branch1][C][F][Branch1]''
embeddings: False # This turns on the embeddings for the conditioning properties
cfg: False # This turns on the classifier-free guidance. ! If this is true, then embeddings must also be true !
local_paths.pre_processed_data: ${paths.data_root}/training_data/${experiment.name}/prepend_preprocessed_data.parquet
local_paths.train_data_encoding: ${paths.data_root}/training_data/${experiment.name}/prepend_train_encoding
properties: [] # This is the list of properties to condition on

#conditioning possibilities: ['nbo_P', 'nmr_P', 'pyr_P', 'fmo_mu', 'vmin_r', 'volume', 'fmo_eta', 
#'fukui_m', 'fukui_p', 'nuesp_P', 'somo_rc', 'nbo_P_rc', 'pyr_alpha', 'qpole_amp', 'vbur_vbur', 
#'Pint_P_min', 'sterimol_L', 'sterimol_B1', 'sterimol_B5', 'dipolemoment', 'efgtens_xx_P', 
#'efgtens_yy_P', 'nbo_bd_e_max', 'nbo_lp_P_occ', 'qpoletens_yy', 'E_solv_elstat', 'nbo_bds_e_avg', 
#'sterimol_burL', 'nbo_bd_occ_avg', 'sterimol_burB5', 'vbur_ovbur_min', 'vbur_qvbur_min', 
#'nbo_bds_occ_max', 'vbur_ratio_vbur_vtot', 'mol_wt', 'sa_score']
