name: prepend
prepend: True # This turns on the prepending of the conditioning properties e.g., '[vbur_vbur_bin_3|3][F][C][Branch1][C][F][Branch1]''
embeddings: False # This turns on the embeddings for the conditioning properties
cfg: False # This turns on the classifier-free guidance. ! If this is true, then embeddings must also be true !
local_paths.pre_processed_data: ${paths.data_root}/training_data/prepend_preprocessed_data.parquet
local_paths.train_data_encoding: ${paths.data_root}/training_data/prepend_train_encoding
properties: {} # This is the list of properties to condition on
