name: Format & Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python & cache pip
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        uses: pre-commit/action@v4
        with:
          extra_args: "--all-files"
